# Generated by Django 4.2.21 on 2025-05-14 20:05

from django.db import migrations, models
import subject_app.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255, validators=[subject_app.validators.validate_subject_format])),
                ('professor', models.CharField(default='Mr.Cahan', max_length=255, validators=[subject_app.validators.validate_professor_format])),
            ],
        ),
    ]
