# Generated by Django 4.2.21 on 2025-05-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
        ('student_app', '0005_alter_student_locker_combination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(related_name='students', to='subject_app.subject'),
        ),
    ]
