# Generated by Django 4.2.21 on 2025-05-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_student_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subjects',
        ),
    ]
