# Generated by Django 4.2.21 on 2025-05-14 20:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject_app', '0001_initial'),
        ('student_app', '0006_student_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=100, max_digits=3, validators=[django.core.validators.MaxValueValidator(100.0)])),
                ('a_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='subject_app.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_app.student')),
            ],
        ),
    ]
